### ISSUE TITLE
Support for Ilias V5.3.2

### ISSUE THREAD

**Issue by dassagichnicht** [fi3te/ILIASDownloaderAndroid#3]
Hi everyone,
since the ilias got updated to Version 5.3.2 the login doesn't work anymore. Does anybody know what has changed and how to fix the problem?
Thank you very much.

**Comment by dassagichnicht** [comment]
This is the error:
Error during login. Maybe wrong Server or wrong client id (not username)

and I'm pretty sure that I entered them correctly because I just copied the URL from the Ilias Login Page.

**Comment by kekru** [comment]
Hi @dassagichnicht, could you try it with the ILIAS Downloader desktop version?
http://whiledo.de/index.php?p=iliasdownloader2
There you get a more detailed error. Maybe that helps to understand, what went wrong

**Comment by dassagichnicht** [comment]
I just tried it again and now it works suddendly although I didn't make any changes.
Thank you for getting in touch to solve the problem.
